// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreFoundation/CoreFoundation.h>
#import <CFNetwork/CFNetwork.h>
#import <CoreAudio/CoreAudio.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) window;
-(IBAction) navigation_controller;
-(IBAction) painting_controller;
-(IBAction) main_storyboard;

@end

@interface PaintingController: UIViewController

@property IBOutlet id painting_view;

-(IBAction) viewDidLoad;
-(IBAction) select_color:(id) sender;
-(IBAction) selected_color;
-(IBAction) stroke_gesture_changed:(id) stroke_gesture_recognizer;
-(IBAction) color_buttons;

@end

@interface Painting: NSObject
-(IBAction) initialize;
-(IBAction) continue_stroke:(id) point;
-(IBAction) current_stroke;

@end

@interface Stroke: NSObject
-(IBAction) add_point:(id) point;
-(IBAction) start_point;

@end

@interface PaintingView: UIView
-(IBAction) drawRect:(id) rectangle;
-(IBAction) draw_stroke:(id) stroke;

@end

@interface StrokeGestureRecognizer: UIGestureRecognizer
@end

