// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation PaintingController
@end

@implementation Painting
@end

@implementation Stroke
@end

@implementation PaintingView
@end

@implementation StrokeGestureRecognizer
@end

